#!/usr/bin/env bash
# debugging Nginx web server
cfg=\
"server {
listen 80 default_server;
listen [::]:80 default_server;
root /usr/share/nginx/html;
index index.html index.htm;
server_name localhost;
location / {
}
}"
echo "$cfg" > sudo tee /etc/nginx/sites-enabled/default
sudo service nginx restart
