#!/usr/bin/env bash
# script that displays "To infinity and beyond" indefinitely,
# "I am invincible!!!" when receiving a SIGTERM signal
while :
do
	trap "echo I am invincible!!!" SIGTERM
	echo "To infinity and beyond"
	sleep 2
done
