#!/usr/bin/env bash
#The script is displaying "Best School" 10 timees
i=1
while [ $i -le 10 ]
do
	if [ $i == 4 ]
	then
		echo "bad luck"
	elif [ $i == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
